### ISSUE TITLE
Model was not sent to NeuronCore (function load)

### ISSUE THREAD

**Issue by jpoberhauser** [aws/aws-neuron-sdk#325] opened 2021-09-14 18:19 UTC
Hello,

I am having an issue that has been partially addressed [here](https://forums.aws.amazon.com/thread.jspa?threadID=337999&tstart=0). 

This happens when running a neuron-compiled yolov4 model, but it only happens when we try to load the model before giving the neuron cores time to fully load (at least that is the current hypothesis).

The observed behavior is the following:

```
>>> model = torch.jit.load(buffer)
[W neuron_op_v2.cpp:133] Warning: Neuron runtime could not be initialized. Model was not sent to NeuronCore (function load)
```

The weird thing is that the model still loads and successfully sends predictions for images sent for inference, but it returns the same exact box and confidence level every single time. The issue for our use case is that we load these models based on an AMI used in auto-scaling so this happens in some cases but not in others, making it hard to trace down. 

I hope someone can guide me in the right direction here but my questions are:

1. Is there a way to figure out if the `model` object is somehow corrupted at load time using python/pytorch code?
2. Once this issue is found, is the best thing to do on the ASG instance to automatically run `$ sudo systemctl status neuron-rtd`  or to follow [these instructions](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-runtime/nrt-troubleshoot.html#neuron-driver-installation-fails) to automatically re-install and the re-attempt  to load the model?

Here are some outputs on versions:
```
$ sudo apt list | grep neuron

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

aws-neuron-dkms/unknown 2.1.5.0 amd64 [upgradable from: 1.5.0.0]
aws-neuron-k8-plugin/unknown 1.6.22.0 amd64
aws-neuron-k8-scheduler/unknown 1.6.22.0 amd64
aws-neuron-runtime/unknown 1.6.24.0 amd64 [upgradable from: 1.5.0.0]
aws-neuron-runtime-base/unknown 1.6.21.0 amd64 [upgradable from: 1.5.1.0]
aws-neuron-tools/unknown 1.7.25.0 amd64 [upgradable from: 1.6.1.0]
neuron/bionic 7.5-1 amd64
neuron-dev/bionic 7.5-1 amd64
python3-neuron/bionic 7.5-1 amd64
```

Thank you very much for your help in advance!

**Comment by mrnikwaws** [comment] 2021-09-15 16:40
Hi @jpoberhauser,

Thanks for the questions.  

1. No, there is no way to explicitly scan a saved or loaded model to detect model corruption.  In this case the error is due to the neuron runtime not being accessible to torch-neuron, but if you have a case of a corrupt model please share it and we'll look at the experience and make sure it is robust.

2. Yes, currently the recommended practice is to check the status of the neuron runtime daemon, and if it is not running to start it.  In the case of repeated issues we would recommend restarting it.  

More broadly we recommend staying up to date with all packages (including the runtime) and confirming in your own release pipeline that there are no performance regressions or unintended changes in behavior of neuron components.

I'm following up on some aspects of your question and I'll post again if there is more to add.

**Comment by mrnikwaws** [comment] 2021-09-15 20:37
In addition care needs to be taken if you are making an instance or a container 'live' for inference.

For example when spinning up an AMI or docker container you need to check the status of the Neuron runtime daemon to confirm it is running before making that instance available.  Normally this is the minimally correct option.

If your kernel version has been updated you may need to re-install the Neuron driver.  While doing this at startup is a reasonable fallback (say if the runtime does not start after 60 seconds) it would be better to rebuild and test your AMI or container with the correctly re-installed driver after a kernel update to minimize startup time.

**Comment by jpoberhauser** [comment] 2021-09-16 13:30
@mrnikwaws I appreciate your answers, that all makes a lot of sense. I will definitely add status checks of the Neuron runtime daemon to confirm its running before making an instance available. Do you have any recommendations on how to do that? Or would the best thing to do be something like:

run `sudo systemctl status neuron-rtd` at start, if  output signals it is up and running, then I make the instance available?

Thanks once again for your recommendations here, I really appreciate it.

**Comment by mrnikwaws** [comment] 2021-09-16 22:40
Hi @jpoberhauser.  

Yes, just like that.  We're looking at some ways to improve this experience in this area for torch-neuron, so please watch out for future releases and release notes

**Comment by jpoberhauser** [comment] 2021-09-17 13:43
Ok thanks once again for your help. I ended up creating the following "startup.sh" just in case you see any glaring mistakes or if someone else finds it useful for now I will leave in this comment:

```
#!/bin/bash
source activate aws_neuron_pytorch_p36 
cd /home/ubuntu/
OUTPUT=$(systemctl status neuron-rtd)
echo "status command has been called!" >> output_log.txt

while [[ $OUTPUT != *"Active: active"* ]]
do
  echo "neuron-rtd is not active yet, waiting 5 seconds and  attempting again" >> output_log.txt
  sleep 5
  OUTPUT=$(systemctl status neuron-rtd)
  echo "${OUTPUT}"
done
#### once its healthy do:
echo "system is healthy, running generic_server_load_model.py" >> output_log.txt
source activate aws_neuron_pytorch_p36 && cd /home/ubuntu/ && python generic_server_load_model.py  >> /home/ubuntu/output.log 2>&1
```

**Comment by mrnikwaws** [comment] 2021-09-17 17:59
Hi @jpoberhauser,

Yes - this looks good.  I would consider adding the following for production use:

* The driver is not working after some timeout (say 60 to 120 seconds) - maybe the kernel got updated?  As a last ditch try reinstalling the runtime daemon
* Do you have some other mechanism to detect servers that don't come up?  You could trigger telemetry of some kind if it makes sense after a timeout

This ought to work as is though ...

**Comment by mrnikwaws** [comment] 2021-09-20 17:31
Closing this issue - please feel free to re-open if you have more questions

**Closed by mrnikwaws** 2021-09-20 17:31 UTC
