### ISSUE TITLE
Compiling Pytorch ConvTranspose2D mysteriously fails 

### ISSUE THREAD

**Issue by usamec** [aws/aws-neuron-sdk#398] opened 2022-02-22 12:29 UTC
ConvTranspose2D from Pytorch (which should be supported given support of `aten::_convolution`) fails in certain channels, input size configurations.

For example following program fails:
```
import torch
import torch.nn as nn
import torch_neuron

net = nn.ConvTranspose2d(256, 128, 2, stride=2)
net.eval()

inp = torch.randn((1,256,32,32))

model_neuron = torch.neuron.trace(
    net,
    example_inputs=[inp],
    fallback=False,
)

print(model_neuron(inp).shape)
```

The error is:
```
INFO:Neuron:Compiling module ConvTranspose2d with neuron-cc
INFO:Neuron:Compiling with command line: '/home/vboza/miniconda3/envs/pipeline/bin/neuron-cc compile /tmp/tmp14dodnpg/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmp14dodnpg/graph_def.neff --io-config {"inputs": {"input:0": [[1, 256, 32, 32], "float32"]}, "outputs": ["transpose_1:0"]} --verbose 35'
.02/22/2022 12:27:28 PM ERROR 8902 [neuron-cc]: Failed to parse model /tmp/tmp14dodnpg/graph_def.pb: Traceback (most recent call last):
  [bt] (8) /home/vboza/miniconda3/envs/pipeline/lib/python3.7/site-packages/tvm/libtvm.so(TVMFuncCall+0x52) [0x7ff9403b7d72]
  [bt] (7) /home/vboza/miniconda3/envs/pipeline/lib/python3.7/site-packages/tvm/libtvm.so(+0xbd2f09) [0x7ff9401c7f09]
  [bt] (6) /home/vboza/miniconda3/envs/pipeline/lib/python3.7/site-packages/tvm/libtvm.so(tvm::relay::InferType(tvm::relay::Expr const&, tvm::relay::Module const&)+0x430) [0x7ff9401c7d30]
  [bt] (5) /home/vboza/miniconda3/envs/pipeline/lib/python3.7/site-packages/tvm/libtvm.so(+0x96533f) [0x7ff93ff5a33f]
  [bt] (4) /home/vboza/miniconda3/envs/pipeline/lib/python3.7/site-packages/tvm/libtvm.so(+0x96493d) [0x7ff93ff5993d]
  [bt] (3) /home/vboza/miniconda3/envs/pipeline/lib/python3.7/site-packages/tvm/libtvm.so(tvm::relay::InferType(tvm::relay::Function const&, tvm::relay::Module const&, tvm::relay::GlobalVar const&)+0x349) [0x7ff9401c8359]
  [bt] (2) /home/vboza/miniconda3/envs/pipeline/lib/python3.7/site-packages/tvm/libtvm.so(+0xbd2713) [0x7ff9401c7713]
  [bt] (1) /home/vboza/miniconda3/envs/pipeline/lib/python3.7/site-packages/tvm/libtvm.so(+0x933a53) [0x7ff93ff28a53]
  [bt] (0) /home/vboza/miniconda3/envs/pipeline/lib/python3.7/site-packages/tvm/libtvm.so(+0x5edf95) [0x7ff93fbe2f95]
  File "/opt/brazil-pkg-cache/packages/DmlcTvm/DmlcTvm-1.9.1.0/AL2_x86_64/generic-flavor/src/src/relay/ir/error.cc", line 112
TVMError: 
Error(s) have occurred. We have annotated the program with them:

In `main`: 
v0.0.1
%9 = fn (%input:0: Tensor[(1, 256, 32, 32), float32], %conv2d_transpose/filter:0: Tensor[(2, 2, 128, 256), float32], %BiasAdd/bias:0: Tensor[(128,), float32]) {
  %0 = transpose(%input:0, framework_op_name="transpose", output_tensors_name=["transpose:0"], input_tensors_name=[], framework_op_debug_info="transpose", axes=[0, 2, 3, 1]) // 
  %1 = transpose(%0, framework_op_name="", output_tensors_name=[], input_tensors_name=[], framework_op_debug_info="conv2d_transpose", axes=[0, 3, 1, 2]) // 
  %2 = transpose(%conv2d_transpose/filter:0, framework_op_name="", output_tensors_name=[], input_tensors_name=[], framework_op_debug_info="conv2d_transpose", axes=[3, 2, 0, 1]) // 
  %3 = nn.conv2d_transpose(%1, %2, framework_op_name="", output_tensors_name=[], input_tensors_name=[], framework_op_debug_info="conv2d_transpose", channels=128, kernel_size=[2, 2], strides=[2, 2]) // 
  %4 = transpose(%3, framework_op_name="conv2d_transpose", output_tensors_name=["conv2d_transpose:0"], input_tensors_name=[], framework_op_debug_info="conv2d_transpose", axes=[0, 2, 3, 1]) // 
  %5 = strided_slice(%4, framework_op_name="", output_tensors_name=[], input_tensors_name=[], framework_op_debug_info="strided_slice", begin=[0, 0, 0, 0], end=[1, 64, 64, 64], strides=[1, 1, 1, 1]) // 
  %6 = reshape(%5, framework_op_name="strided_slice", output_tensors_name=["strided_slice:0"], input_tensors_name=[], framework_op_debug_info="strided_slice", newshape=[1, 64, 64, 64]) // 
  %7 = add(%6, %BiasAdd/bias:0, framework_op_name="BiasAdd", output_tensors_name=["BiasAdd:0"], input_tensors_name=[], framework_op_debug_info="BiasAdd", axis=0) // Incompatible broadcast type TensorType([1, 64, 64, 64], float32) and TensorType([128], float32); 
  %8 = transpose(%7, framework_op_name="transpose_1", output_tensors_name=["transpose_1:0"], input_tensors_name=[], framework_op_debug_info="transpose_1", axes=[0, 3, 1, 2]) // 
  %8
}
%9
 (TVMError)

Compiler status ERROR
INFO:Neuron:Compile command returned: 1
Traceback (most recent call last):
  File "dbgx.py", line 13, in <module>
    fallback=False,
  File "/home/vboza/miniconda3/envs/pipeline/lib/python3.7/site-packages/torch_neuron/convert.py", line 120, in trace
    runnable = cu.subgraph_compiler(func, example_inputs, **compile_kwargs)
  File "/home/vboza/miniconda3/envs/pipeline/lib/python3.7/site-packages/torch_neuron/decorators.py", line 221, in trace
    'neuron-cc failed with the following command line call:\n{}'.format(command))
subprocess.SubprocessError: neuron-cc failed with the following command line call:
/home/vboza/miniconda3/envs/pipeline/bin/neuron-cc compile /tmp/tmp14dodnpg/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmp14dodnpg/graph_def.neff --io-config '{"inputs": {"input:0": [[1, 256, 32, 32], "float32"]}, "outputs": ["transpose_1:0"]}' --verbose 35
```

Howeven when input size is changed to `(1,256,64,64)` everything works.
Also when number of output channels is changed to 64 everything works.

Environment:
```
neuron-cc==1.9.1.0+5f09e5c8e
torch==1.10.1
torch-neuron==1.10.1.2.1.7.0
```

```
$ neuron-cc -V
Neuron Compiler version 1.9.1.0+5f09e5c8e

HWM version 1.9.0.0-0
NEFF version Dynamic
TVM version 1.9.1.0+0
NumPy version 1.20.0
MXNet not available
TF not available
```

**Comment by jeffhataws** [comment] 2022-02-22 19:53
Thanks @usamec for reporting the issue. We have reproduced the problem and will root-cause it.

**Comment by mrnikwaws** [comment] 2022-03-08 01:05
Hi Vlado,

We believe we've resolved this issue internally, and it should appear in a future release.  We'll update this ticket when the change is released.

**Comment by bluesky314** [comment] 2022-03-08 09:36
We are facing same issue. When will this be released?

**Comment by aws-taylor** [comment] 2022-03-14 17:19
Hello @bluesky314,

 We do not publish dates for future releases, however you can take a look at our past releases to get a sense of our historic release cadence - https://github.com/aws/aws-neuron-sdk/releases.
 
Regards,
Taylor

**Comment by aws-joshim** [comment] 2022-04-05 18:36
Hello @bluesky314, the latest release of Neuron SDK (1.18.0) https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/releasecontent.html should have the fix for the ConvTranspose2D compilation issue that you encountered. Please let us know if this resolves your issue

**Comment by aws-joshim** [comment] 2022-04-06 22:37
@bluesky314 closing the ticket since the Neuron 1.18.0 release fixes the issue. Please open a new ticket if you run into an y other issues

**Closed by aws-joshim** 2022-04-06 22:37 UTC

**Comment by heylamourding** [comment] 2022-11-18 03:41
Hi team, I also encountered this issue. Could u help check? 

I think it is Neuron 1.18.0. 
```
pip install torch==1.11.0
pip install torchvision==0.12.0
pip install torch-neuron==1.11.0.2.3.0.0
pip install torch-model-archiver==0.6.1
pip install neuron_cc==1.11.7
```


```
INFO:Neuron:PyTorch to TF conversion failed to resolve function on aten::_convolution with inputs [<tf.Tensor '0:0' shape=(1, 256, 32, 32) dtype=float32>, <tf.Tensor 'prim_Constant/Const:0' shape=(256, 128, 2, 2) dtype=float32>, <tf.Tensor 'prim_Constant_1/Const:0' shape=(128,) dtype=float32>, [2, 2], [0, 0], [1, 1], True, [0, 0], 1, False, False, True, True]
INFO:Neuron:Exception = Got an unexpected keyword argument 'value'
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [5], in <cell line: 10>()
      6 net.eval()
      8 inp = torch.randn((1,256,32,32))
---> 10 model_neuron = torch.neuron.trace(
     11     net,
     12     example_inputs=[inp],
     13     fallback=False,
     14 )
     16 print(model_neuron(inp).shape)

File /usr/local/lib/python3.8/dist-packages/torch_neuron/convert.py:124, in trace(func, example_inputs, fallback, op_whitelist, minimum_segment_size, subgraph_builder_function, subgraph_inputs_pruning, skip_compiler, debug_must_trace, allow_no_ops_on_neuron, compiler_workdir, dynamic_batch_size, compiler_timeout, _neuron_trace, compiler_args, optimizations, verbose, **kwargs)
    122 logger.debug("skip_inference_context trace without fallback at {}".format(get_file_and_line()))
    123 converted = to_graph(func, example_inputs, **kwargs)
--> 124 runnable = cu.subgraph_compiler(converted, example_inputs, **compile_kwargs)
    125 if _neuron_trace is neuron_test_trace:
    126     return runnable

File /usr/local/lib/python3.8/dist-packages/torch_neuron/decorators.py:80, in trace(func, example_inputs, compiler_args, compiler_timeout, verbose, compiler_workdir, use_cached_compiler_output, dynamic_batch_size, autoloop_spec, _internal_return_neff, optimizations, *args, **kwargs)
     75 with torch_trace_error_handler():
     76     jit_trace = jit_trace_function(func, example_inputs, **kwargs)
     78 preprocessor, postprocessor, input_tensors, output_tensors, \
     79     _, graph, _ = \
---> 80     transform_torch_graph_to_tensorflow(jit_trace, example_inputs, neuron_graph=func, **kwargs)
     82 graph_def = graph.as_graph_def()
     84 if optimizations is not None:

File /usr/local/lib/python3.8/dist-packages/torch_neuron/decorators.py:574, in transform_torch_graph_to_tensorflow(jit_trace, example_inputs, neuron_graph, **kwargs)
    571     log.info("PyTorch to TF conversion failed to resolve function on {} with inputs {}".format(
    572         op.node.kind(), tensor_inputs))
    573     log.info("Exception = {}".format(e))
--> 574     raise e
    575 if not node.hasMultipleOutputs():
    576     tensor_outputs = [tensor_outputs]

File /usr/local/lib/python3.8/dist-packages/torch_neuron/decorators.py:568, in transform_torch_graph_to_tensorflow(jit_trace, example_inputs, neuron_graph, **kwargs)
    566 operators.append(op)
    567 try:
--> 568     tensor_outputs = local_func(op, *tensor_inputs)
    569 except Exception as e:
    570     # When function resolution fails switch logging to debug
    571     log.info("PyTorch to TF conversion failed to resolve function on {} with inputs {}".format(
    572         op.node.kind(), tensor_inputs))

File /usr/local/lib/python3.8/dist-packages/torch_neuron/ops/aten.py:148, in _convolution(op, tensor, weight, bias, stride, padding, dilation, transposed, output_padding, groups, benchmark, deterministic, cudnn_enabled, allow_tf32)
    146 # Permute dimensions for TF implementation:  NCHW -> NHWC
    147 transposed_output_shape = [batch_size, h_out, w_out, int(c_out)]
--> 148 tensor = tf.nn.conv2d_transpose(
    149     value=tensor, filter=weight, output_shape=transposed_output_shape,
    150     strides=strides, padding='VALID', dilations=dilations)
    151 # compute the output shape expected by PT.
    152 pt_h_out = h_out - (stride[0] * 2 + 2) * int(padding[0])

File /usr/local/lib/python3.8/dist-packages/tensorflow/python/util/traceback_utils.py:153, in filter_traceback.<locals>.error_handler(*args, **kwargs)
    151 except Exception as e:
    152   filtered_tb = _process_traceback_frames(e.__traceback__)
--> 153   raise e.with_traceback(filtered_tb) from None
    154 finally:
    155   del filtered_tb

File /usr/local/lib/python3.8/dist-packages/tensorflow/python/util/dispatch.py:1076, in add_dispatch_support.<locals>.decorator.<locals>.op_dispatch_handler(*args, **kwargs)
   1074 if iterable_params is not None:
   1075   args, kwargs = replace_iterable_params(args, kwargs, iterable_params)
-> 1076 result = api_dispatcher.Dispatch(args, kwargs)
   1077 if result is not NotImplemented:
   1078   return result

TypeError: Got an unexpected keyword argument 'value'
```
