### ISSUE TITLE
Custom Yolov4 on Neuro

### ISSUE THREAD

**Issue by minhtcai** [aws/aws-neuron-sdk#262] opened 2021-04-28 22:15 UTC
Hi AWS Neuro team,

We're trying to compile a custom yolov4 model  and deploy in a Inferentia server.
Using the tutorial here: https://docs.aws.amazon.com/dlami/latest/devguide/tutorial-inferentia-tf-neuron.html

+Yolov4 COCO - Pytorch - Save Model Ok, Compile Model OK
+Yolov4 COCO - Tensorflow - Save Model OK, Compile Model OK 

+Yolov4 Custom - Pytorch - Save Model Ok in pth, can't compile, get error (RuntimeError: Error(s) in loading state_dict for Yolov4: and then a bunch of keys)

+Yolov4 Custom - Tensorflow - Save Model OK in TF (using repo https://github.com/hunglc007/tensorflow-yolov4-tflite), can't compile (got TF 2.0 error)

+Yolov4 Custom - Tensorflow - Can't save model using yolo_v4_coco_saved_model.py, I've changed the weights path, and number of class (got KeyError)
Traceback (most recent call last):
  File "yolo_v4_coco_saved_model.py", line 1102, in <module>
    main()
  File "yolo_v4_coco_saved_model.py", line 1081, in main
    torch_weights = rename_weights(checkpoint)
  File "yolo_v4_coco_saved_model.py", line 693, in rename_weights
    pt_weights[new_name] = pth_weights[name]
KeyError: 'down1.conv1.conv.0.weight'

Do you guy have any tutorial of either compile TF 2 model or convert darknet weights of custom model to .pb using TF 1.15.5?
Thank you very much!

#191

**Comment by aws-diamant** [comment] 2021-05-02 20:40
Hi @minhtcai,
The reason you see the compilation error is that the provided model checkpoint file in the tutorial is only meant to be used for the specific model in the tutorial.
For your custom YOLOv4 model, you should call torch.neuron.trace for your pytorch model directly, or call tfn.saved_model.compile on your tensorflow SavedModel.

We are actively working on Tensorflow 2.x support in Neuron, you can track progress [here](https://github.com/aws/aws-neuron-sdk/projects/2).

**Comment by minhtcai** [comment] 2021-05-04 21:33
Thank you for the reply, I was able to load my custom model in but when I run:
torch.neuron.analyze_model(model, example_inputs=[image])
I got the error below, could you please help on that:

Traceback (most recent call last):
  File "compile_custom_pytorch.py", line 23, in <module>
    torch.neuron.analyze_model(model, example_inputs=[image]) #,subgraph_builder_function=subgraph_builder_function)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/model_support.py", line 227, in analyze_model
    neuron_graph = convert.to_graph(model, example_inputs)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/convert.py", line 228, in to_graph
    jit_trace = torch.jit.trace(func_or_mod, example_inputs)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/jit/_trace.py", line 742, in trace
    _module_class,
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/jit/_trace.py", line 966, in trace_module
    _module_class,
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/jit/_trace.py", line 335, in _check_trace
    _compilation_unit=torch._C.CompilationUnit(),
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/jit/_trace.py", line 928, in trace_module
    module = make_module(mod, _module_class, _compilation_unit)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/jit/_trace.py", line 560, in make_module
    return _module_class(mod, _compilation_unit=_compilation_unit)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/jit/_trace.py", line 1040, in __init__
    submodule, TracedModule, _compilation_unit=None
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/jit/_trace.py", line 560, in make_module
    return _module_class(mod, _compilation_unit=_compilation_unit)
  File "/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch/jit/_trace.py", line 988, in __init__
    assert isinstance(orig, torch.nn.Module)
AssertionError

**Comment by micwade-aws** [comment] 2021-05-10 19:12
Hi @minhtcai - The source of this error is that the Module being traced is not derived from torch.nn.Module. This is a requirement to tracing PyTorch classes.  Has anything been changed from the tutorial code?  If so, can you describe what has changed?

**Comment by minhtcai** [comment] 2021-05-14 18:38
Thanks for the suggestions, I was able to replicate the performance ~5000 images/40 seconds with Pytorch for COCO.
For our custome model. I was able to compile and make it run on single images. However, I was trying to run it with the 5000 COCO images and it just stucks there then die eventually. The change I made are just these line:

#model = Yolov4(yolov4conv137weight=None, n_classes=80, inference=True)
model = Yolov4(yolov4conv137weight=None, n_classes=2, inference=True)
#weightfile = "./yolo_v4.pth"
weightfile = "./yolov4-test.pth"
pretrained_dict = torch.load(weightfile, map_location=torch.device('cpu'))
model.load_state_dict(pretrained_dict,strict=False)
model.eval()


def subgraph_builder_function(node):
    return 'YoloLayer' not in node.name

model_neuron = torch.neuron.trace(model, image, subgraph_builder_function=subgraph_builder_function)
#model_neuron.save('yolo_v4_neuron.pt')
model_neuron.save('yolo_v4_neuron_test.pt')

**Comment by aws-joshim** [comment] 2021-05-14 22:27
@minhtcai we will look into your model changes to reproduce the problem that and get back

**Comment by awsryg** [comment] 2021-05-19 00:08
Hi @minhtcai , we did reproduce the failure. It seems that the model is producing lots of boxed output, creating memory pressure. Could you please try, in the post processing, to raise the value of score_threashold? It is set to 0.5. Try some value between that and 1?

**Comment by minhtcai** [comment] 2021-05-19 20:36
Thank you for the suggestion, I was able to run it, however it is still ~280s, my custom model I just changed the number of output, it should reach the same performance as the tutorial right? Do you think there could be other reason that caused this? ==================== Performance Measurement ==================== 
Finished inference on 5000 images in 279.43 seconds =================================================================

**Comment by awsryg** [comment] 2021-05-19 22:28
Hi @minhtcai , is it possible that you are looking at the performance of the validation results, rather than the benchmarking results? See the benchmarking code at the bottom of the tutorial which loads 4 models?

**Comment by minhtcai** [comment] 2021-05-20 14:29
Thanks, that works. However I still got: 
Duration:  98.08147072792053
Images Per Second: 50.97802839712788

Is there anyway for troubleshooting this?
Also, I wonder how did you find the prob with the memory? Would love to know more about the debugging process, thank you!

**Comment by aws-stdun** [comment] 2021-05-24 19:36
Hi @minhtcai, I was able to run the tutorial with your changes above and get the expected performance.
```
Duration:  37.07992482185364
Images Per Second: 134.84385483578896
```
Is it possible you've made additional changes to the code? 
Can you verify that you have 0 models loaded before running the benchmarking code?
(You can use `neuron-top` to look, and `neuron-cli reset` to clear any loaded models beforehand.)

> Is there anyway for troubleshooting this?
> Also, I wonder how did you find the prob with the memory? Would love to know more about the debugging process, thank you!

We re-ran the tutorial with your configuration while monitoring system metrics, which showed growing memory utilization. The tutorial involves storing results into a dictionary for validation, so this was a good candidate to investigate for memory issues. Our randomly initialized model with 2 output classes makes many thousands of (random) predictions / inference, hence the large memory footprint. In general, we unfortunately can't provide assistance with debugging your models, unless it's directly related to an issue with Neuron.

**Comment by minhtcai** [comment] 2021-05-25 20:17
Thank you @aws-stdun 
I verified that I didn't make any changes to the codes (except loading our model) and 0 models loaded before running.
Is there any chance the problem comes from the compiling part? 
Meanwhile, I also observed that while running the benchmark(), the Inf cores are always just around 25%-27% each core.
![Screenshot from 2021-05-25 15-51-15](https://user-images.githubusercontent.com/38054203/119559999-63e77780-bd71-11eb-95a7-8b484552e247.png)

**Comment by aws-stdun** [comment] 2021-05-25 20:56
It looks like you may be CPU-bound. Based on this screenshot, it appears you are running on an inf1.2xlarge. Is that correct?
From [the tutorial](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-frameworks/pytorch-neuron/tutorials/pytorch_yolov4_tutorial.html):

> To enable faster enviroment setup, you will run the tutorial on an inf1.6xlarge instance to enable both compilation and deployment (inference) on the same instance.

**Comment by minhtcai** [comment] 2021-05-25 22:59
Thanks @aws-stdun 
So from that tutorial in the benchmark(), I can see that n_cores = 4, does it mean that inf1.2xlarge could reach the same performance?

I just switched to inf1.6xlarge, tried to run with 16 cores but for some reasons, the Neuro core % drops dramatically and varies between 1-10% while CPU always around 100%
![Screenshot from 2021-05-25 18-30-06](https://user-images.githubusercontent.com/38054203/119576851-84223100-bd87-11eb-97a9-c73d570af55b.png)

I then cleared and then tried 4 cores again and it's really slow. So I restarted the instance, changed back to 2xlarge and the performance comebacks at 25-27%. So does it mean that we can reach the performance as the tutorial if we can use 100% of cores? And what's the role of CPU? Do you think the bottleneck could be reprocessing?

My code
[aws_neuron.zip](https://github.com/aws/aws-neuron-sdk/files/6542722/aws_neuron.zip)

**Comment by aws-stdun** [comment] 2021-05-28 22:52
Hi @minhtcai,
Running your script with 4 NeuronCores on an inf1.6xlarge:
```
$ python aws_neuron.py
Duration:  38.12312722206116
Images Per Second: 131.15398353539558
```
The reason for poor performance at 16 cores is that you have loaded all 16 models onto a single Neuron device using 4 NeuronCores (notice in `neuron-top` they are all on `nd0`). You need to set the [NeuronCore Group Sizes](https://awsdocs-neuron.readthedocs-hosted.com/en/1.13.0/neuron-guide/neuron-frameworks/tensorflow-neuron/tutorials/tutorial-tensorflow-NeuronCore-Group.html) appropriately.
With 16 NeuronCores I modified your script as shown below:
```
def benchmark():
    “”"
    Run a benchmark on the entire COCO dataset against the neuron model.
    “”"
    n_cores = 16
    os.environ[‘NEURONCORE_GROUP_SIZES’] = ‘,’.join([‘1’] * n_cores)
    n_threads = mp.cpu_count() * 2
```
Results:
```
$ python aws_neuron.py
Duration:  15.275112390518188
Images Per Second: 327.3298337957683
```
I’m not sure why you are seeing such high CPU utilization, as your screenshot isn’t sorted by CPU%. When I run your code, I see around 30-40% utilization.

**Comment by minhtcai** [comment] 2021-06-01 14:44
@aws-stdun Thanks for your suggestion!
I was trying to run inf1.2xlarge on a brand new instance and got the same speed result. 
My first steps are downloading the COCO datasets, install pycocotools, then run my code. What do you think could be the reason here?

![Screenshot from 2021-06-01 09-31-45](https://user-images.githubusercontent.com/38054203/120342416-c4246f00-c2c5-11eb-9f04-672bad9e319b.png)

**Comment by awsrjh** [comment] 2021-06-03 19:51
Hi minhtcai

perhaps we can speed up this process by talking more directly.

please reach out to us at aws-neuron-support@amazon.com and we can see how to help.

**Comment by aws-stdun** [comment] 2021-06-07 21:46
I'm closing this after meeting with @minhtcai  + @mrnikwaws offline. We determined the issue here was an older version of `neuron-rtd` from March 3rd. After [upgrading the runtime](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-intro/install-pytorch.html), performance moved in line with our expectations.

**Closed by aws-stdun** 2021-06-07 21:46 UTC

**Comment by minhtcai** [comment] 2021-06-07 21:53
Amazing support, thank you all guys!
