### ISSUE TITLE
Error when predecting on Tensorflow serving

### ISSUE THREAD

**Issue by ssoli2020** [aws/aws-neuron-sdk#80] opened 2020-02-13 01:40 UTC
Hi,

Last code example fails in AWS blog: https://itnext.io/a-first-look-at-aws-inferentia-b9672e8f8b8f 

Below is the output error:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/aws_neuron_tensorflow_p36/lib/python3.6/site-packages/PIL/Image.py", line 2584, in open
fp.seek(0)
AttributeError: 'tuple' object has no attribute 'seek'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "tfserving_rsnet50.py", line 16, in <module>
  img = image.load_img(img_file, target_size=(224, 224))
  File "/home/ec2-user/anaconda3/envs/aws_neuron_tensorflow_p36/lib/python3.6/site-packages/keras_preprocessing/image/utils.py", line 110, in load_img
  img = pil_image.open(path)
  File "/home/ec2-user/anaconda3/envs/aws_neuron_tensorflow_p36/lib/python3.6/site-packages/PIL/Image.py", line 2586, in open
fp = io.BytesIO(fp.read())
AttributeError: 'tuple' object has no attribute 'read'

Thanks

**Comment by aws-zejdaj** [comment] 2020-02-14 14:47
Thank you for bringing it to our attention. We have reproduced the error and identified the cause. Working on a fix.

**Comment by jeffhataws** [comment] 2020-02-21 23:33
ssoli2020,
The last code example in the blog has some typos that is now fixed. Please try again and let us know if there's any further assistance needed. 
Thanks.

**Closed by jeffhataws** 2020-02-21 23:33 UTC
