### ISSUE TITLE
Internal Compiler Error on Neuron-CC in Inf1 Conda Environment

### ISSUE THREAD

**Issue by navyamehta** [aws/aws-neuron-sdk#256] opened 2021-03-31 19:07 UTC
I run an export on a pre-trained Pytorch model (7 inputs, 2 outputs) in the aws_neuron_pytorch_p36 conda environment on AWS EC2 Inf1 instances. The trace runs successfully but compilation fails with an assertion error. (The model has previously been exported to TensorRT so none of the dynamic size issues etc. exist)

Full Trace:
```
INFO:Neuron:The following operations are currently supported in torch-neuron for this model:
INFO:Neuron:aten::sub
INFO:Neuron:prim::Constant
INFO:Neuron:aten::size
INFO:Neuron:aten::avg_pool2d
INFO:Neuron:prim::TupleConstruct
INFO:Neuron:aten::sigmoid
INFO:Neuron:aten::unsqueeze
INFO:Neuron:aten::relu
INFO:Neuron:aten::_convolution
INFO:Neuron:aten::to
INFO:Neuron:aten::mul
INFO:Neuron:prim::TupleUnpack
INFO:Neuron:aten::upsample_nearest2d
INFO:Neuron:aten::permute
INFO:Neuron:aten::zeros
INFO:Neuron:aten::softmax
INFO:Neuron:aten::cat
INFO:Neuron:aten::batch_norm
INFO:Neuron:aten::Int
INFO:Neuron:prim::NumToTensor
INFO:Neuron:aten::sum
INFO:Neuron:prim::ListConstruct
INFO:Neuron:aten::view
INFO:Neuron:100.00% of all operations (including primitives) (526 of 526) are supported
INFO:Neuron:100.00% of arithmetic operations (67 of 67) are supported
INFO:Neuron:All operators are compiled by neuron-cc (this does not guarantee that neuron-cc will successfully compile)
INFO:Neuron:Number of arithmetic operators (pre-compilation) before = 67, fused = 67, percent fused = 100.0%
INFO:Neuron:compiling function _NeuronGraph$256 with neuron-cc
INFO:Neuron:Compiling with command line: '/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/bin/neuron-cc compile /tmp/tmp6nevbgly/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmp6nevbgly/graph_def.neff --io-config {"inputs": {"0:0": [[32, 10, 64, 64], "float32"], "1:0": [[1, 10, 64, 64], "float32"], "2:0": [[32, 11, 3, 64, 64], "float32"], "tensor.7:0": [[32, 11, 64, 64, 2], "float32"]}, "outputs": ["Sigmoid:0", "transpose_79:0"]} --verbose 35'
.03/31/2021 07:06:27 PM ERROR [neuron-cc]: ***************************************************************
03/31/2021 07:06:27 PM ERROR [neuron-cc]:  An Internal Compiler Error has occurred
03/31/2021 07:06:27 PM ERROR [neuron-cc]: ***************************************************************
03/31/2021 07:06:27 PM ERROR [neuron-cc]: 
03/31/2021 07:06:27 PM ERROR [neuron-cc]: Error message:  Expect tensor contract the last operator!
03/31/2021 07:06:27 PM ERROR [neuron-cc]: 
03/31/2021 07:06:27 PM ERROR [neuron-cc]: Error class:    AssertionError
03/31/2021 07:06:27 PM ERROR [neuron-cc]: Error location: job.Frontend.4
03/31/2021 07:06:27 PM ERROR [neuron-cc]: Command line:   /home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/bin/neuron-cc compile /tmp/tmp6nevbgly/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmp6nevbgly/graph_def.neff --io-config '{"inputs": {"0:0": [[32, 10, 64, 64], "float32"], "1:0": [[1, 10, 64, 64], "float32"], "2:0": [[32, 11, 3, 64, 64], "float32"], "tensor.7:0": [[32, 11, 64, 64, 2], "float32"]}, "outputs": ["Sigmoid:0", "transpose_79:0"]}' --verbose 35
03/31/2021 07:06:27 PM ERROR [neuron-cc]: 
03/31/2021 07:06:27 PM ERROR [neuron-cc]: Internal details:
03/31/2021 07:06:27 PM ERROR [neuron-cc]:   File "neuroncc/driver/Job.py", line 242, in neuroncc.driver.Job.runSingleInputFn
03/31/2021 07:06:27 PM ERROR [neuron-cc]:   File "neuroncc/driver/jobs/Frontend.py", line 236, in neuroncc.driver.jobs.Frontend.Frontend.runSingleInput
03/31/2021 07:06:27 PM ERROR [neuron-cc]:   File "neuroncc/driver/jobs/Frontend.py", line 237, in neuroncc.driver.jobs.Frontend.Frontend.runSingleInput
03/31/2021 07:06:27 PM ERROR [neuron-cc]:   File "neuroncc/driver/jobs/Frontend.py", line 247, in neuroncc.driver.jobs.Frontend.Frontend.runSingleInput
03/31/2021 07:06:27 PM ERROR [neuron-cc]:   File "neuroncc/driver/jobs/Frontend.py", line 215, in neuroncc.driver.jobs.Frontend.Frontend.runSingleInput.tensorize
03/31/2021 07:06:27 PM ERROR [neuron-cc]:   File "neuroncc/starfish/penguin/Frontend.py", line 248, in neuroncc.starfish.penguin.Frontend.tensorizeRelay
03/31/2021 07:06:27 PM ERROR [neuron-cc]:   File "neuroncc/starfish/penguin/Frontend.py", line 249, in neuroncc.starfish.penguin.Frontend.tensorizeRelay
03/31/2021 07:06:27 PM ERROR [neuron-cc]:   File "neuroncc/starfish/penguin/Frontend.py", line 269, in neuroncc.starfish.penguin.Frontend.tensorizeRelay
03/31/2021 07:06:27 PM ERROR [neuron-cc]:   File "neuroncc/starfish/penguin/Frontend.py", line 104, in neuroncc.starfish.penguin.Frontend.compile
03/31/2021 07:06:27 PM ERROR [neuron-cc]:   File "neuroncc/starfish/penguin/targets/tonga/CodeGenFlow.py", line 112, in neuroncc.starfish.penguin.targets.tonga.CodeGenFlow.codegen_prepare
03/31/2021 07:06:27 PM ERROR [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 123, in neuroncc.starfish.penguin.DotTransform.DotTransform.runOnFunction
03/31/2021 07:06:27 PM ERROR [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 175, in neuroncc.starfish.penguin.DotTransform.DotTransform.run_with_exception_handling
03/31/2021 07:06:27 PM ERROR [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 157, in neuroncc.starfish.penguin.DotTransform.DotTransform.run_with_exception_handling
03/31/2021 07:06:27 PM ERROR [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 182, in neuroncc.starfish.penguin.DotTransform.DotTransform.timed_run_
03/31/2021 07:06:27 PM ERROR [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 184, in neuroncc.starfish.penguin.DotTransform.DotTransform.timed_run_
03/31/2021 07:06:27 PM ERROR [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 185, in neuroncc.starfish.penguin.DotTransform.DotTransform.timed_run_
03/31/2021 07:06:27 PM ERROR [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 192, in neuroncc.starfish.penguin.DotTransform.DotTransform.run_
03/31/2021 07:06:27 PM ERROR [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 271, in neuroncc.starfish.penguin.DotTransform.DotTransform.transformFunction
03/31/2021 07:06:27 PM ERROR [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 265, in neuroncc.starfish.penguin.DotTransform.DotTransform.runTransforms
03/31/2021 07:06:27 PM ERROR [neuron-cc]:   File "neuroncc/starfish/penguin/targets/tonga/passes/TongaSizeTiling.py", line 1334, in neuroncc.starfish.penguin.targets.tonga.passes.TongaSizeTiling.TongaSizeTiling.transformStmts
03/31/2021 07:06:27 PM ERROR [neuron-cc]:   File "neuroncc/starfish/penguin/targets/tonga/passes/TongaSizeTiling.py", line 1169, in neuroncc.starfish.penguin.targets.tonga.passes.TongaSizeTiling.TongaSizeTiling.transformDAG
03/31/2021 07:06:27 PM ERROR [neuron-cc]:   File "neuroncc/starfish/penguin/targets/tonga/passes/TongaSizeTiling.py", line 562, in neuroncc.starfish.penguin.targets.tonga.passes.TongaSizeTiling.TongaSizeTiling.packInstsToMatMulMacro
03/31/2021 07:06:27 PM ERROR [neuron-cc]: 
03/31/2021 07:06:27 PM ERROR [neuron-cc]: Version information:
03/31/2021 07:06:27 PM ERROR [neuron-cc]:   Neuron Compiler version 1.2.7.0+eaf2e01fb
03/31/2021 07:06:27 PM ERROR [neuron-cc]:   
03/31/2021 07:06:27 PM ERROR [neuron-cc]:   HWM version 1.2.6.0-0
03/31/2021 07:06:27 PM ERROR [neuron-cc]:   NEFF version 1.0
03/31/2021 07:06:27 PM ERROR [neuron-cc]:   TVM version 1.2.6.0+0
03/31/2021 07:06:27 PM ERROR [neuron-cc]:   NumPy version 1.18.1
03/31/2021 07:06:27 PM ERROR [neuron-cc]:   MXNet not available
03/31/2021 07:06:27 PM ERROR [neuron-cc]:   TF not available
03/31/2021 07:06:27 PM ERROR [neuron-cc]:   ONNX not available
03/31/2021 07:06:27 PM ERROR [neuron-cc]: 
03/31/2021 07:06:27 PM ERROR [neuron-cc]: Artifacts stored in: /tmp/tmp6nevbgly

Compiler status ERROR
INFO:Neuron:Compile command returned: 1
```

Thank you!

**Comment by jeffhataws** [comment] 2021-03-31 21:23
Hi Navya, thanks for filing this issue. The error message indicates a compiler error. Please use compiler_workdir='<path>' argument in torch.neuron.trace function call to dump compiler artifacts into <path>. After running the compilation, please send us an archive of compiled artifacts directory to aws-neuron-support@amazon.com. We will debug further and get back to you.

**Comment by aws-joshim** [comment] 2021-05-17 18:38
Hi Navya, please reach out to the Neuron team at  aws-neuron-support@amazon.com with the compiled artifacts if you need assistance on your compilation error

**Comment by aws-joshim** [comment] 2021-05-17 22:21
Hi Navya, this ticket was closed accidently. We are actively working on resolving the compile error that you reported

**Comment by awsilya** [comment] 2021-06-07 16:29
Hi Navya, our team confirmed that this model can be successfully compiled for batch size = 1 using the latest compiler release.  We still have difficulties compiling for batch size = 32 and are actively working on it.  Please try compiling for a batch size that you intend to use in production and let us know the outcome.

As a workaround for larger batch you could try compiling for NC pipeline by passing neuron-core-pipeline = X (try 2 or 4).  Please keep in mind that a model compiled for NC pipeline will occupy the number of NC specified in the compiler option.

**Comment by mrnikwaws** [comment] 2021-06-23 21:09
Hi Navya,

Did the batch 1 solution on the last release help you?  It is often the case that models compiled and run on neuron need a smaller batch sizes than on GPU.

I plan to close this issue if I'm not seeing further activity, since there does seem to be a solution to the problem for the model.

I am happy to provide more support if you believe the higher batch size is key to your use case.

**Comment by micwade-aws** [comment] 2021-07-22 18:55
@navyamehta - Please re-open this if still blocked.

**Closed by micwade-aws** 2021-07-22 18:55 UTC
