### ISSUE TITLE
set core 1 to inference in data parallel(4 cores) but only use 1

### ISSUE THREAD

**Issue by manchann** [aws/aws-neuron-sdk#321] opened 2021-09-06 05:14 UTC
I know that when I set core =1 and compile model, it performs inference tasks in data parallel. In fact, if I set the compiled batch 1 (resnet50), it perform data parallel on four cores. However, if the compiled batch is 64, only one is used.
Is there a reason for this or a bug?

using 'neuron-top' command for check core usage.
- compiled batch : 1
![image](https://user-images.githubusercontent.com/28581495/132163716-7e9c2668-618a-425f-8856-a37418dc0b89.png)

- compiled batch: 64
![image](https://user-images.githubusercontent.com/28581495/132164005-75d07388-f87f-4465-8289-af776d9312f9.png)

**Comment by kmu-leeky** [comment] 2021-09-13 03:31
same situation here. Setting the neuron core as 1 results in different core utilization with respect to different batch sizes. Is it an expected behavior?

**Comment by aws-renfu** [comment] 2021-09-13 15:04
> I know that when I set core =1 and compile model, it performs inference tasks in data parallel. In fact, if I set the compiled batch 1 (resnet50), it perform data parallel on four cores. However, if the compiled batch is 64, only one is used.
> Is there a reason for this or a bug?
> 
> using 'neuron-top' command for check core usage.
> 
> * compiled batch : 1
>   ![image](https://user-images.githubusercontent.com/28581495/132163716-7e9c2668-618a-425f-8856-a37418dc0b89.png)
> * compiled batch: 64
>   ![image](https://user-images.githubusercontent.com/28581495/132164005-75d07388-f87f-4465-8289-af776d9312f9.png)

Could you tell us what's the image size? A larger batch size will increase both the code size and the intermediate tensor sizes, and therefore increase the accelerator memory requirement. Further, a large input size (aka image size) will also increase the accelerator memory requirement as well. Thanks.

**Comment by manchann** [comment] 2021-09-14 04:03
Thank you for answer my question I used imagenet dataset 224 x 224 size.
What I understand by your answer, the neuron device memory have limitation and can not accept input data in all cores.
Then is there any quantitative value about neuron device memory?

**Comment by mrnikwaws** [comment] 2021-09-22 16:48
Hi @manchann,

I'm going to defer for now answering your specific question about memory, as some of the team are working on some more general guidance on that point.

It looks like you are working to find the optimal batch size for a model.  When using tensorflow-neuron and searching for the best batch size we recommend loading the maximum number of cores following the guidance in https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-frameworks/tensorflow-neuron/tutorials/tutorial-tensorflow-NeuronCore-Group.html#tensorflow-neurocore-group and running tests with each batch size, working up from a low value.  We call this a 'sweep' of batch sizes.

With tensorflow-neuron Resnet50 with 224x224 input achieves peak throughput around batch 5, so best is to sweep batch from about 4 to 8. 

You can find more details in https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/technotes/neuroncore-batching.html as well as an example how to sweep in https://awsdocs-neuron.readthedocs-hosted.com/en/latest/src/examples/tensorflow/keras_resnet50/keras_resnet50.html

The differential behavior that you saw (the smaller batch size loaded on multiple cores) was due to some automated behavior in tensorflow-neuron which we're reviewing.  The above guidance is best for optimizing you batch size

**Comment by manchann** [comment] 2021-09-23 02:40
Ok I'll be waiting for general guidance about neuron device memory thanks !

**Comment by aws-maens** [comment] 2021-09-30 16:56
Hi @manchann,
In Neuron release 1.17.0 we are planning to provide a fix for tensorflow-neuron that will solve the issue that you are facing. Meanwhile we suggest you will use smaller batch sizes which will reduce the memory footprint of the model. Please note that for Neuron, small batch size is recommended to achieve optimized performance.

Other alternative that you can try is to specify NEURONCORE_GROUP_SIZES=1,1,1,1 when running your application and loading your model 4 times in sequence inside your application. for more information please see tutorial at : https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-frameworks/tensorflow-neuron/tutorials/tutorial-tensorflow-NeuronCore-Group.html

**Comment by aws-maens** [comment] 2021-11-01 21:49
Hi @manchann,

With the introduction of Neuron Runtime 2.x in Neuron release 1.16.0, this issue should be resolved.
Please upgrade to latest Neuron release and let us know if this solves your issue.

**Comment by aws-owinop** [comment] 2021-11-03 18:01
Hi @manchann, 

Closing this issue. Kindly reopen if you still face similar issue with Neuron Runtime 2.x with the Neuron 1.16.0 release.

**Closed by aws-owinop** 2021-11-03 18:01 UTC
