### ISSUE TITLE
Default MaxPoolingOp only supports NHWC on device type CPU

### ISSUE THREAD

**Issue by whatdhack** [aws/aws-neuron-sdk#53] opened 2019-12-25 21:36 UTC
Getting  the above error. Is there a way to work around this  error ?  Partial stack trace follows. 

```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Default MaxPoolingOp only supports NHWC on device type CPU
         [[node pool0/MaxPool (defined at /home/ubuntu/anaconda3/envs/aws_neuron_tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
```

**Comment by awsrjh** [comment] 2019-12-26 20:14
Hello,

this is at the heart a limit of Tensorflow (please see: https://github.com/tensorflow/tensorflow/issues/15364 ). 

If this is an issue due to a limitation of  the Neuron compiler which results in the Tensorflow-Neuron falling back to CPU execution for that (sub)graph for you use case, please let us know.

**Comment by whatdhack** [comment] 2019-12-26 20:43
Works with regular Tensorflow CPU environment.  Throws this error only in the  Neuron environment ( e.g. aws_neuron_tensorflow_p36 ).

**Comment by whatdhack** [comment] 2019-12-26 20:45
Buy the way (please see: tensorflow/tensorflow#15364 )  is not a problem in 1.14.

**Comment by jeffhataws** [comment] 2020-01-07 05:41
Thanks for bringing the issue to our attention. We have reproduced the issue and we are fixing it for a future release.

**Comment by jeffhataws** [comment] 2020-02-24 15:58
Hi, this issue has been fixed in our last release. Please see TensorFlow-Neuron release note for 1/27/20 release: https://github.com/aws/aws-neuron-sdk/blob/master/release-notes/tensorflow-neuron.md#1150109970. Please let us know if you have any other issues. Thanks.

**Closed by jeffhataws** 2020-02-24 15:58 UTC
