### ISSUE TITLE
SubprocessError: neuron-cc failed

### ISSUE THREAD

**Issue by C24IO** [aws/aws-neuron-sdk#134] opened 2020-07-18 04:56 UTC
https://github.com/aws/aws-neuron-sdk/blob/6431512195ee3d9c9f42160f7b528bf97103fc0a/src/examples/pytorch/bert_tutorial/tutorial_pretrained_bert.ipynb#L60

```
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:transformers.tokenization_utils_base:Truncation was not explicitely activated but `max_length` is provided a specific value, please use `truncation=True` to explicitely truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
WARNING:transformers.tokenization_utils_base:Truncation was not explicitely activated but `max_length` is provided a specific value, please use `truncation=True` to explicitely truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
INFO:Neuron:Optimize = None
INFO:Neuron:Compiler args type is <class 'list'> value is ['-O2']
INFO:Neuron:compiling module BertForSequenceClassification with neuron-cc
INFO:Neuron:Compiling with command line: '/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/bin/neuron-cc compile /tmp/tmpnfp80ag0/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpnfp80ag0/graph_def.neff --io-config {"inputs": {"input_ids:0": [[1, 128], "int64"], "attention_mask.1:0": [[1, 128], "int64"], "input.2:0": [[1, 128], "int64"]}, "outputs": ["Add_124:0"]} -O2''
---------------------------------------------------------------------------
SubprocessError                           Traceback (most recent call last)
<ipython-input-1-45864823a308> in <module>
     26 
     27 # Run torch.neuron.trace to generate a TorchScript that is optimized by AWS Neuron, using optimization level -O2
---> 28 model_neuron = torch.neuron.trace(model, example_inputs_paraphrase, compiler_args=['-O2'])
     29 
     30 # Verify the TorchScript works on both example inputs

~/anaconda3/envs/aws_neuron_pytorch_p36/lib/python3.6/site-packages/torch_neuron/decorators.py in trace(func, example_inputs, compiler_args, compiler_timeout, optimize, compiler_workdir, use_cached_compiler_output, *args, **kwargs)
    219                 command = ' '.join(shlex.quote(itm) for itm in command)
    220                 raise subprocess.SubprocessError(
--> 221                     'neuron-cc failed with the following command line call:\n{}'.format(command))
    222 
    223     metaneff, neff_ts = compile_from_neff( neff_path, jit_trace, unique_tensor_map, example_inputs, input_tensors, output_tensors )

SubprocessError: neuron-cc failed with the following command line call:
/home/ubuntu/anaconda3/envs/aws_neuron_pytorch_p36/bin/neuron-cc compile /tmp/tmpnfp80ag0/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /tmp/tmpnfp80ag0/graph_def.neff --io-config '{"inputs": {"input_ids:0": [[1, 128], "int64"], "attention_mask.1:0": [[1, 128], "int64"], "input.2:0": [[1, 128], "int64"]}, "outputs": ["Add_124:0"]}' -O2
```

**Comment by AWSNB** [comment] 2020-07-20 03:12
@C24IO  just acknowledging that we saw the issue and we are looking at it, will get back to you soon

**Comment by aws-taylor** [comment] 2020-07-22 17:38
Hello Chaitanya,

 I believe this error is arising because you are attempting to use the tutorial with an older version of the _neuron-cc_ package. Upgrading ought to address your problem. Please let us know if you have any further issues.

`python3 -m pip install --upgrade neuron-cc`

-Taylor

**Comment by NatalliaSpichekovaTR** [comment] 2020-07-23 05:45
HI!
@aws-taylor  I'm facing the same issue and upgrade didn't help me. 

I'm going through a tutorial on adapting PyTorch BERT code with AWS Neuron SDK for EC2 Inf1 instances at https://github.com/aws/aws-neuron-sdk/blob/master/src/examples/pytorch/bert_tutorial/bert_large_mrpc_tutorial.md . I'm using c5n.9xlarge instance. 

At 'Stage 2: Compile BERT for Neuron' there is a notebook 'neuron_bert_mrpc_tutorial.ipynb' to run. But I get 'SubprocessError: neuron-cc failed with the following command line call:
/home/ubuntu/bert_mrpc/torch_compile/bin/neuron-cc compile /home/ubuntu/bert_mrpc/compile/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /home/ubuntu/bert_mrpc/compile/graph_def.neff --io-config '{"inputs": {"input.1:0": [[4, 128, 1024], "float32"], "attention_mask:0": [[4, 1, 1, 128], "float32"]}, "outputs": ["batchnorm_47/add_1:0"]}' --fp32-cast all --verbose=1 --tensor-layout-heuristics=spatial-locality -O2'
error while running a cell with calling a 'compile_bert()' routine.

Here ia a piece of logs:
07/23/2020 05:33:45 AM ERROR [neuron-cc]: ***************************************************************
07/23/2020 05:33:45 AM ERROR [neuron-cc]:  An Internal Compiler Error has occurred
07/23/2020 05:33:45 AM ERROR [neuron-cc]: ***************************************************************
07/23/2020 05:33:45 AM ERROR [neuron-cc]: 
07/23/2020 05:33:45 AM ERROR [neuron-cc]: Error message:  A process in the process pool was terminated abruptly while the future was running or pending.
07/23/2020 05:33:45 AM ERROR [neuron-cc]: 
07/23/2020 05:33:45 AM ERROR [neuron-cc]: Error class:    BrokenProcessPool
07/23/2020 05:33:45 AM ERROR [neuron-cc]: Error location: pipeline.compile.0
07/23/2020 05:33:45 AM ERROR [neuron-cc]: Command line:   /home/ubuntu/bert_mrpc/torch_compile/bin/neuron-cc compile /home/ubuntu/bert_mrpc/compile/graph_def.pb --framework TENSORFLOW --pipeline compile SaveTemps --output /home/ubuntu/bert_mrpc/compile/graph_def.neff --io-config '{"inputs": {"input.1:0": [[4, 128, 1024], "float32"], "attention_mask:0": [[4, 1, 1, 128], "float32"]}, "outputs": ["batchnorm_47/add_1:0"]}' --fp32-cast all --verbose=1 --tensor-layout-heuristics=spatial-locality -O2
07/23/2020 05:33:45 AM ERROR [neuron-cc]: 
07/23/2020 05:33:45 AM ERROR [neuron-cc]: Internal details:
07/23/2020 05:33:45 AM ERROR [neuron-cc]:   File "neuroncc/driver/Job.py", line 234, in neuroncc.driver.Job.runSingleInputFn
07/23/2020 05:33:45 AM ERROR [neuron-cc]:   File "neuroncc/driver/Pipeline.py", line 30, in neuroncc.driver.Pipeline.Pipeline.runSingleInput
07/23/2020 05:33:45 AM ERROR [neuron-cc]:   File "neuroncc/driver/Job.py", line 274, in neuroncc.driver.Job.SingleInputJob.run
07/23/2020 05:33:45 AM ERROR [neuron-cc]:   File "neuroncc/driver/Job.py", line 279, in neuroncc.driver.Job.SingleInputJob.run
07/23/2020 05:33:45 AM ERROR [neuron-cc]:   File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 432, in result
07/23/2020 05:33:45 AM ERROR [neuron-cc]:     return self.__get_result()
07/23/2020 05:33:45 AM ERROR [neuron-cc]:   File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
07/23/2020 05:33:45 AM ERROR [neuron-cc]:     raise self._exception
07/23/2020 05:33:45 AM ERROR [neuron-cc]: 
07/23/2020 05:33:45 AM ERROR [neuron-cc]: Version information:
07/23/2020 05:33:46 AM ERROR [neuron-cc]:   Neuron Compiler version 1.0.16861.0+6021080341
07/23/2020 05:33:46 AM ERROR [neuron-cc]:   
07/23/2020 05:33:46 AM ERROR [neuron-cc]:   HWM version 1.0.1516.0-6020726378
07/23/2020 05:33:46 AM ERROR [neuron-cc]:   NEFF version 1.0
07/23/2020 05:33:46 AM ERROR [neuron-cc]:   TVM version 1.0.2732.0+6020726378
07/23/2020 05:33:46 AM ERROR [neuron-cc]:   NumPy version 1.18.2
07/23/2020 05:33:46 AM ERROR [neuron-cc]:   MXNet not available
07/23/2020 05:33:46 AM ERROR [neuron-cc]:   TF version 1.15.0
07/23/2020 05:33:46 AM ERROR [neuron-cc]:   ONNX not available

Please find screen of the error and logs in the attachment.
[log-neuron-cc.txt](https://github.com/aws/aws-neuron-sdk/files/4964034/log-neuron-cc.txt)
![neuron_subprocess_error](https://user-images.githubusercontent.com/62645581/88255343-ce96d500-ccc0-11ea-836a-2a89b2f79928.png)

**Comment by aws-diamant** [comment] 2020-07-24 15:53
Hello NatalliaSpichekovaTR,

Thanks for sharing this info.
I'm going to try and reproduce your issue, in order to provide better guidance.

Would you mind sharing the following information?
1) Which DLAMI are you using?
2) What torch version? (`python -c "import torch; print(torch.__version__)"`)
3) What torch-neuron version? (`pip show torch-neuron`)

Thanks!
Ron

**Comment by NatalliaSpichekovaTR** [comment] 2020-07-24 16:11
Hi!
Thank you for your response.
I'm using c5n.9xlarge, torch_version is 1.5.1.1.0.251.0, torch-neuron version is 1.0.1386.0.
![image](https://user-images.githubusercontent.com/62645581/88411965-83281800-cde1-11ea-8336-01e22f27c360.png)

**Comment by aws-diamant** [comment] 2020-07-25 05:03
Hello NatalliaSpichekovaTR!

Based on the error log that you posted, it seems that a compiler process was terminated during compilation.
`07/23/2020 05:33:45 AM ERROR [neuron-cc]: Error message: A process in the process pool was terminated abruptly while the future was running or pending.`

I tried to reproduce this issue on my end, but this seems to be working on my machines (tried c5n.9xlarge and also c5.4xlarge).

I suggest that we try to run the BERTBase tutorial, so we can establish a baseline together and then move forward from there (it's a shorter tutorial, with faster compilation time).

Few questions to align on tutorial entry-point:
[1] you are using "AWS Deep Learning AMI (Ubuntu 18.04)", correct?
[2] after connecting to the instance, you ran `source activate aws_neuron_pytorch_p36`, correct?
[3] after that, did you fetch the latest neuron packages? (`conda update torch-neuron`)

If the answer to all three steps is 'yes', then I suggest to continue with the following BERTBase tutorial:
https://github.com/aws/aws-neuron-sdk/blob/master/src/examples/pytorch/bert_tutorial/tutorial_pretrained_bert.ipynb

Once we get this tutorial to finish successfully, it should be much easier to go back to the BERTLarge tutorial and solve the issue.

Please let us know if this works for you. We'll be happy to assist with any problem that you might encounter.

/Ron

![image](https://user-images.githubusercontent.com/23586853/88448627-9ee8e980-cdf4-11ea-9da2-a9c8c36db0f8.png)

**Comment by NatalliaSpichekovaTR** [comment] 2020-08-03 12:12
Hi!
Thank you for your response. 
Actaully I'm using a custom AMI. Neuron SDK was installed according  to the guide https://github.com/aws/aws-neuron-sdk/blob/master/docs/neuron-install-guide.md#user-guide-configuring-linux-for-repository-updates
After Neuron reinstallation, I can successfully go through tutorials 
https://github.com/aws/aws-neuron-sdk/blob/master/src/examples/pytorch/bert_tutorial/tutorial_pretrained_bert.ipynb
https://github.com/aws/aws-neuron-sdk/blob/master/src/examples/pytorch/bert_tutorial/neuron_bert_mrpc_tutorial.ipynb
https://github.com/aws/aws-neuron-sdk/blob/master/src/examples/pytorch/bert_tutorial/neuron_bert_mrpc_benchmark.ipynb
The compiled models run on an inf1.2xlarge instance.

Now I'd like to compile a custom pretrained model with Neuron to run it on Inf1 instance.
The model uses _pytorch- transformers_ v 1.1.0. It is a _bert-large-uncased_ model plus linear layes for classification.
The model is loaded with _from_pretrained_ method and is compiled with _torch.neuron.trace(model_bert, input_test_example2_bert, compiler_args=['O2])_ During compilation I don't get errors, just warnings (screen in the attachment).
After compilation I'm running the compiled code on inf1.2xlarge. I got 
RuntimeError: NeuronDevice::process_nrtd_response: Context=NRTD_CTX_LOAD NRTD response code 'NERR_RESOURCE' (4) The runtime was unable to allocate a resource for the requested operation. Raw runtime error message '[TDRV:hugetlb_cache_get] Could not find free hugetlb node! 

While running the compiled code on inf1.6sxlarge instance, I got RuntimeError: NeuronDevice::process_nrtd_response: Context=NRTD_CTX_INITIALIZE NRTD response code 'NERR_HW_ERROR' (6) There was a hardware error. Please contact AWS support. Raw runtime error message ''

Could you please help to find out why the compiled code doesn't run on inf1? Is it because using _pytorch_transformers_ instead of _transformers_ OR because  compiler options are not suitable for the case?

Please find screens of errors and warnings in the attachment.
<img width="336" alt="compile_warnings" src="https://user-images.githubusercontent.com/62645581/89180547-a8afe100-d59a-11ea-98bb-cd8fd16256f0.png">
<img width="344" alt="inf_2x_error" src="https://user-images.githubusercontent.com/62645581/89180551-a9e10e00-d59a-11ea-941c-2cffbd1345db.png">
<img width="336" alt="inf_6x_error" src="https://user-images.githubusercontent.com/62645581/89180553-aa79a480-d59a-11ea-8b2c-d07b8c465fa2.png">

**Comment by micwade-aws** [comment] 2020-08-03 14:04
@NatalliaSpichekovaTR I recognize the hugetlb error. Would you mind confirming that at least 128 huge pages are configured in your ami?  If it's lower than this, please try increasing the number of huge pages allocated when running your model on the inf1. We have instructions for this here: https://github.com/aws/aws-neuron-sdk/blob/master/docs/neuron-runtime/nrt_start.md#step-3-configure-nr_hugepages

It's possible that you need more that the default recommendation of 128, but unlikely.

The other error you're reporting is more concerning. I'll sync with the team on that error after we confirm the huge pages settings. 

--micwade@

**Comment by NatalliaSpichekovaTR** [comment] 2020-08-03 17:22
Hi!
Thank you for your response.
I was able to run my compiled model on inf.6xlarge after setting vm.nr_hugepages = 16384 and num_hugepages_per_device = 512. 
But logits and loss that are returned by the model before and after compilation differ in the second fraction sign on the same input. Could you please clarify is it expected behaviour or there are some issues with during compilation?

Here are loss and logits returned by the model before compilation:
![image](https://user-images.githubusercontent.com/62645581/89209245-9350ac00-d5c6-11ea-99c0-4367d7f234e3.png)
Here are loss and logits return by the model after compilation on the same input example:
![image](https://user-images.githubusercontent.com/62645581/89209297-af544d80-d5c6-11ea-8405-496f163e0b39.png)

**Comment by aws-joshim** [comment] 2020-08-03 21:53
@NatalliaSpichekovaTR - This difference is expected as compiler will cast native float32 tensors before compilation to bfloat16 post compilation

**Comment by aws-joshim** [comment] 2020-08-05 19:27
@NatalliaSpichekovaTR checking in if you are able to run inferences with your compiled model on the inf.6xlarge instance

**Comment by NatalliaSpichekovaTR** [comment] 2020-08-06 04:53
yes, I was able to run inference for a test example on inf1.6xlarge. Later I''m going to run more tests on real data with my compiled model. In case of any issues, I'll contanct you.

**Comment by aws-joshim** [comment] 2020-08-06 14:18
@NatalliaSpichekovaTR , thanks for getting back. I will go ahead and close this issue since your neuron-cc compilation completed successfully and you were able to run inferences on the inf.6xlarge instance. We will be happy to assist you on any questions on your test with the compiled model. Please confirm that is ok.

**Comment by NatalliaSpichekovaTR** [comment] 2020-08-06 14:19
Yes, it's ok.
Thank you very much for your assistance!

**Closed** 2020-08-06 14:44 UTC
