### ISSUE TITLE
Model converted but gives some warnings and inference not working.

### ISSUE THREAD

**Issue by felixhusen** [aws/aws-neuron-sdk#408] opened 2022-03-17 02:05 UTC
I was trying to compile my trained SSD MobileNet v2 320x320 tensorflow 2 model. I used the script below to compile my model.

```
import os
import shutil
import numpy as np
import tensorflow.neuron as tfn

# Create a workspace
WORKSPACE = '../tf_models'
os.makedirs(WORKSPACE, exist_ok=True)

# Prepare export directory (old one removed)
model_dir = os.path.join(WORKSPACE, 'table_detection_ssd')
compiled_model_dir = os.path.join(WORKSPACE, 'table_detection_neuron')
shutil.rmtree(compiled_model_dir, ignore_errors=True)

input_tensor = np.zeros([4, 320, 320, 3], dtype='float32')
feeds = {'input_tensor': input_tensor}
tfn.saved_model.compile(model_dir, compiled_model_dir, model_feed_dict=feeds)

# Prepare SavedModel for uploading to Inf1 instance
shutil.make_archive(compiled_model_dir, 'zip', WORKSPACE, 'table_detection_neuron')
```

However, it gives me several warnings and when I tried to run inference with tensorflow_serving_neuron server it does not give any results.

```
2022-03-17 02:00:22.719504: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING:tensorflow:Selecting default SignatureDef "serving_default" when loading SavedModel ../tf_models/table_detection_ssd
2022-03-17 02:00:30.446677: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-03-17 02:00:30.446918: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-03-17 02:00:30.470137: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2999995000 Hz
2022-03-17 02:00:32.699350: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-03-17 02:00:32.699454: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-03-17 02:00:33.006167: I tensorflow/neuron/grappler/convert/segment.cc:456] There are 181 ops of 43 different types in the graph that are not compiled by neuron-cc: GreaterEqual, Where, Greater, Maximum, Range, Minimum, Split, Pack, Squeeze, TopKV2, GatherV2, Switch, Mul, LoopCond, LogicalAnd, NoOp, TensorListFromTensor, TensorListStack, Pad, StridedSlice, Less, Merge, AddV2, Enter, NextIteration, Sum, TensorListSetItem, Exit, TensorListGetItem, Identity, NonMaxSuppressionV5, Sub, ExpandDims, Fill, ResizeBilinear, Shape, Slice, Cast, Unpack, ConcatV2, Reshape, Placeholder, Select, (For more information see https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/neuron-cc-ops/neuron-cc-ops-tensorflow.html).
2022-03-17 02:00:33.982245: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-03-17 02:00:33.982365: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2022-03-17 02:00:35.014826: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING:tensorflow:
################### Attention!!! ###################
According to semantic analysis, this model requires
a neuron-cc 1.3 based fall-back code generator.
####################################################
WARNING:tensorflow:
################### Attention!!! ###################
According to semantic analysis, this model requires
a neuron-cc 1.3 based fall-back code generator.
####################################################
WARNING:absl:Found untraced functions such as restored_function_body, restored_function_body, restored_function_body, restored_function_body, restored_function_body while saving (showing 5 of 125). These functions will not be directly callable after loading.
INFO:tensorflow:Assets written to: ../tf_models/table_detection_neuron/assets
INFO:tensorflow:Assets written to: ../tf_models/table_detection_neuron/assets
INFO:tensorflow:Successfully converted ../tf_models/table_detection_ssd to ../tf_models/table_detection_neuron
INFO:tensorflow:Successfully converted ../tf_models/table_detection_ssd to ../tf_models/table_detection_neuron
```

I'm using tensorflow 2.5.2 with tensorflow-neuron==2.5.2.2.1.14.0 and neuron-cc==1.9.1.0+5f09e5c8e

**Comment by aws-diamant** [comment] 2022-03-21 00:23
Hi @felixhusen  and thanks for opening the issue.

We were able to reproduce the issue based on 'SSD MobileNet v2 320x320' [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md).
Could you please confirm that this model is a good representation of what you're trying to compile?

We've identified two lowering issues with this model, and fixed both. The fix should be available in one of our next releases.
I'm keeping the ticket open for now, and we will notify you once the fix is published.

Thanks,
Ron

**Comment by felixhusen** [comment] 2022-03-21 00:42
Hi Ron, @aws-diamant

That is correct. I trained my custom model with the base model 'SSD MobileNet v2 320x320' from the link that you provided.
I can confirm that is a good representation of what I was trying to compile.

Thank you.

**Comment by aws-diamant** [comment] 2022-03-28 01:12
Hi @felixhusen ,

An internal fix had been applied, and this model is now passing internal testing. The fix will be available in one of the upcoming releases.
We're keeping the issue open for now, and will close once the release is out.

**Comment by hannanjgaws** [comment] 2022-04-29 23:16
Hi @felixhusen, 

The latest Neuron SDK release v1.19.0 https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/releasecontent.html has a fix for the error you are encountering. We will close this ticket because the fix should resolve the issue you are hitting. Please open a new ticket if you run into any further issues with your model.

**Closed by hannanjgaws** 2022-04-29 23:16 UTC
