### ISSUE TITLE
Ultralytics yolov5 complilation, using weights attempt_load not working with torch.load()

### ISSUE THREAD

**Issue by anubhavdavid** [aws/aws-neuron-sdk#277] opened 2021-06-15 08:44 UTC
If I'm directly loading the pre-trained weights using torch.hub.load, the compilation for neuron graph seems to be working, but if I download the weights using attempt_load and then load them with torch.load(), it give the error:

torch.nn.modules.module.ModuleAttributeError: 'Detect' object has no attribute 'inplace'

Compiler Version=> 1.3.7.0+fc8e67ab4
- OS Version= Ubuntu
- Python version=3.6
- ML Framework (MXNet/Tensorflow/Pytorch) being used= Pytorch
- ML Framework version= 1.7.1

**Comment by jeffhataws** [comment] 2021-06-15 15:47
Hi anubhavdavid, thank you for filing the issue. We will take a look.

**Comment by mrnikwaws** [comment] 2021-06-16 18:05
Hi Anubhav,

Thanks for the query. 

I noticed this issue (which is unrelated to neuron): https://github.com/pytorch/pytorch/issues/46971.  It appears the issue here is caused by training a model and saving it in an earlier version of PyTorch and then loading in the current version (or a recent one).  The comments indicate that loading just the state dictionary may be productive, if this sound like it matches your use of the model.  While the error is not identical it looks similar.

Please also note the compilation notes for YOLOv5 here: https://github.com/aws/aws-neuron-sdk/issues/253, and the upstreamed change to YOLOv5 here: https://github.com/ultralytics/yolov5/pull/2953.  It was merged here: https://github.com/ultralytics/yolov5/pull/2982.  If you are working with a recent version of YOLOv5 then I believe this should 'just work' for you.

On saving and loading in neuron, typically you'd do something like this:
```
    model_neuron = torch.neuron.trace( ... )
    model_neuron.save('my_filename.pt')
    model_neuron_loaded = torch.jit.load('my_filename.pt')
```
There is a difference between https://pytorch.org/docs/stable/generated/torch.load.html and https://pytorch.org/docs/stable/generated/torch.jit.load.html.  I don't think this is the source of your issue, but worth noting to avoid any future issues.

Thanks for trying torch-neuron, and I hope this information will help you resolve the problem.  

If you are still having problems and you believe it is related to Neuron, please share some code that reproduces the issue and we'll take a deeper look.

**Comment by mrnikwaws** [comment] 2021-06-23 17:38
Hi Anubhav,

Since we haven't heard back on this issue for a week I am going to close it.  Please feel free to reopen it if you have some additional information to share.

**Closed by mrnikwaws** 2021-06-23 17:38 UTC
